name: test-all
on:
    push:
        branches:
            - feature/*
            - develop
            - main
        paths:
            - "packages/**"
            - ".github/workflows/**"
            - "package.json"
            - "yarn.lock"
            - "!**.md"
    pull_request:
        branches:
            - develop
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ">=20.0.0"
                  cache: "yarn"
            - uses: goto-bus-stop/setup-zig@v2
              with:
                  version: 0.12.0
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - run: yarn install --immutable
            - run: yarn test
            - run: yarn tool:imports
